# Generated by Django 3.0.6 on 2020-05-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
